################################################################################
#
# Vagrantfile
#
################################################################################

# Buildroot version to use
RELEASE='2021.02.6'

### Change here for more memory/cores ###
VM_MEMORY=5144
VM_CORES=4

Vagrant.configure('2') do |config|
	# ssh keys
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	# Define the Virtual VM
	config.vm.box = 'ubuntu/bionic64'
	config.vm.synced_folder ".", "/vagrant", disabled: true
	vagrant_root = File.join(File.dirname(__FILE__), "..", "..")
	config.vm.provision "shell", inline: "mkdir -p /home/vagrant/buildroot"
	config.vm.synced_folder vagrant_root, "/home/vagrant/buildroot"

	config.vm.provider :vmware_fusion do |v, override|
		v.vmx['memsize'] = VM_MEMORY
		v.vmx['numvcpus'] = VM_CORES
	end

	config.vm.provider :virtualbox do |v, override|
		v.memory = VM_MEMORY
		v.cpus = VM_CORES

		required_plugins = %w( vagrant-vbguest )
		required_plugins.each do |plugin|
		  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
	end

	config.vm.provision 'shell' do |s|
		s.inline = 'echo Setting up machine name'

		config.vm.provider :vmware_fusion do |v, override|
			v.vmx['displayname'] = "Buildroot #{RELEASE}"
		end

		config.vm.provider :virtualbox do |v, override|
			v.name = "Buildroot #{RELEASE}"
		end
	end

	config.vm.provision 'shell', privileged: true, inline:
		"sed -i 's|deb http://us.archive.ubuntu.com/ubuntu/|deb mirror://mirrors.ubuntu.com/mirrors.txt|g' /etc/apt/sources.list
		dpkg --add-architecture i386
		apt-get -q update
		apt-get purge -q -y snapd lxcfs lxd ubuntu-core-launcher snap-confine
		apt-get -q -y install build-essential libncurses5-dev \
			git bzr cvs mercurial subversion libc6:i386 unzip bc
		apt-get -q -y autoremove
		apt-get -q -y clean
		update-locale LC_ALL=C"

end
