name: buildroot-style-check

on:
  pull_request:
    branches: [ 'chargepoint/**' ]

jobs:
  buildroot_package_check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Python setup
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: 3.9
      - name: Run buildroot package checks
        run: |
          pip install --upgrade pip
          pip install --upgrade flake8 six python-magic
          python3 utils/check-package -v **/*.mk
          python3 utils/check-package -v **/Config.in*

